# Generated by Django 4.2.4 on 2023-09-17 06:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN')], max_length=25)),
                ('product_img', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
